# Generated by Django 5.1.7 on 2025-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_event',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_event',
            field=models.IntegerField(default=0),
        ),
    ]
